workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    merge-code-samples-into-spec:
        inputs:
            - location: registry.speakeasyapi.dev/plexapi/plexapi/plexapi:main
        overlays:
            - location: ./mintlify-overlay.yaml
            - location: registry.speakeasyapi.dev/plexapi/plexapi/code-samples-php-plexphp:main
            - location: registry.speakeasyapi.dev/plexapi/plexapi/code-samples-ruby-plexruby:main
            - location: registry.speakeasyapi.dev/plexapi/plexapi/code-samples-go-plexgo:main
            - location: registry.speakeasyapi.dev/plexapi/plexapi/code-samples-java-plexjava:main
            - location: registry.speakeasyapi.dev/plexapi/plexapi/code-samples-typescript-plexjs:main
        output: ./openapi-with-code-samples.yaml
        registry:
            location: registry.speakeasyapi.dev/plexapi/plexapi/merge-code-samples-into-spec
targets: {}
