workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
  # Plex-API:
  # inputs:
  #   - location: registry.speakeasyapi.dev/lukehagar/lukehagar/plex-api:latest
  # # overlays:
  # # - location: ./mintlify-overlay.yaml
  # # - location: https://github.com/LukeHagar/plexjs/raw/main/codeSamples.yaml
  # output: plexapi
targets: {}
