workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    merge-code-samples-into-spec:
        inputs:
            - location: registry.speakeasyapi.dev/lukehagar/lukehagar/plex-api
        overlays:
            - location: registry.speakeasyapi.dev/lukehagar/lukehagar/code-samples-php-plexphp:main
            - location: registry.speakeasyapi.dev/lukehagar/lukehagar/code-samples-ruby-plexruby:main
            - location: registry.speakeasyapi.dev/lukehagar/lukehagar/code-samples-go-plexgo:main
            - location: registry.speakeasyapi.dev/lukehagar/lukehagar/code-samples-java-plexjava:main
            - location: registry.speakeasyapi.dev/lukehagar/lukehagar/code-samples-typescript-plexjs:main
        output: ./openapi-with-code-samples.yaml
        registry:
            location: registry.speakeasyapi.dev/lukehagar/lukehagar/merge-code-samples-into-spec
targets: {}
